### ISSUE TITLE
Make a Ten Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/make-a-ten#1]
## Design
- [x] **Sim folder and design doc created** (Date: 02/24/2015)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account  
  - [x] Place design doc in the sim folder 
- [x] **Legacy sim docs/info gathered**
- [x] **Learning goals and standards identified** (Date: 02/26/2015) 
- [x] **Design concept complete**  (Date: 03/03/2015) 
- [x] **Wireframes complete** (Date: 03/09/2015) 
- [x] **Mockups complete** (Date: 04/30/2015) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Interviews complete** (Date: 12/19/16) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 01/15/2017)  
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Check compatible activities  
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher guide
  - [x] Compatible activities ([author spreadsheet](https://docs.google.com/spreadsheets/d/1AOc1vy0HfEeJQ9sT0Vs_sr6dqmsEHfq7HWUBGQV_VQA/edit#gid=0))
  - [ ] Sim primer
  - [x] Verify credits
- [x] **Update [Gooru PhET URL tracker](https://docs.google.com/spreadsheets/d/19sffdKj9NdMuFdp3NcFeJmPyDY-3KsoM7Pbu84gUVtw/edit#gid=636879231)**
- [x] **Add to Edmodo**

## Implementation
- [x] **Sim repo created** (Date: 05/11/2015 ) 
  - [x] Simula-rasa used to create basic project structure
  - [x] Grunt unpublished-readme run to create the initial readme file
  - [x] Collaborators added (such as 3rd party, QA team, designers, etc)
  - [x] Standard label set applied
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
- [x] **Initial development started** (Date: 05/13/2015) 
- [x] **Sim feature complete** (Date: 11/11/2016) 
- [x] **Code review complete** (Date: 11/11/2016) 
  - [x] Code review checklist
  - [x] Model description 
- [x] **Published** (Date: 02/28/2017) 
  - [x] Update repo README to published template

## QA
- [x] **Dev testing complete** (Date: 01/13/2017) 
- [x] **First release candidate** (Date: 01/25/2017) 
  - [x] Place in matrix in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
  - [x] Test matrix deemed complete

**Comment by jonathanolson** [comment]
Handled all open issues and completed code review tasks, waiting on testing/feedback. Unassigning myself.

**Comment by ariel-phet** [comment]
Sim primer issue made, closing
